backend:
  name: github
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

publish_mode: editorial_workflow

media_folder: "site/static/images/uploads" # Folder where user uploaded files should go
public_folder: "images/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Fecha de publicacion", name: "date", widget: "datetime"}
      - {label: "Resumen", name: "description", widget: "text"}
      - {label: "Banner", name: "image", widget: "image", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}
